global:
  edition: ce

  hosts:
    domain: gitlab.example.com

  ingress:
    enabled: true
    configureCertmanager: false
    class: nginx
    tls:
      enabled: false

certmanager:
  install: false

gitlab:
  upgradeCheck:
    enabled: false
