global:
  edition: ce

  hosts:
    domain: gitlab.example.com
    externalIP: a4a53e32c53b44052a77b412eed28880-1079592521.us-east-1.elb.amazonaws.com

  ingress:
    enabled: true
    configureCertmanager: false
    class: nginx
    tls:
      enabled: false

certmanager:
  install: false
